repos:
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        language_version: python3.11

  # Temporarily comment Ruff block to allow commit:
  # - repo: https://github.com/astral-sh/ruff-pre-commit
  #   rev: v0.6.9
  #   hooks:
  #     - id: ruff
  #       args: [--fix]
