# Auto-generated by ComfyVN export pipeline
# timeline: main
# project: phase4
# generated_at: 2025-10-23T02:03:47.557187+00:00

label start:
    call intro
    call ending
    return

label intro:
    "..."
    return

label ending:
    "..."
    return
