# Auto-generated by ComfyVN export pipeline
# timeline: main
# project: phase4
# generated_at: 2025-10-21T23:43:35.143451+00:00

label start:
    call intro
    call ending
    return

label intro:
    "..."
    return

label ending:
    "..."
    return
